import { JobStatusMark } from "@/components/JobStatusMark";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, CheckCircle2, CircleAlert, Loader2, Printer } from "lucide-react";
import { Link, useRoute } from "wouter";

export default function CustomerJobStatus() {
  const [, params] = useRoute("/status/:token");
  const token = params?.token ?? "";
  const jobQuery = trpc.printKori.publicJob.useQuery({ publicStatusToken: token }, { refetchInterval: 5000 });
  if (jobQuery.isLoading) return <div className="public-center"><Loader2 className="h-7 w-7 animate-spin" /> Checking request status…</div>;
  if (!jobQuery.data) return <div className="public-center"><div><p className="kicker">PrintKori / Status</p><h1 className="mt-3 text-4xl font-black tracking-[-0.06em]">REQUEST NOT FOUND.</h1></div></div>;
  const job = jobQuery.data;
  const finished = job.status === "Completed" || job.status === "Failed" || job.status === "Cancelled";
  return <main className="min-h-screen bg-[#fbfbfa] p-5 text-[#111111] sm:p-8"><div className="mx-auto max-w-3xl border border-black bg-white"><header className="flex items-center justify-between border-b border-black p-6"><div><p className="kicker">{job.shopName}</p><h1 className="mt-1 text-2xl font-black tracking-[-0.05em]">YOUR PRINT REQUEST</h1></div><Printer className="h-8 w-8" /></header><div className="grid md:grid-cols-[1fr_220px]"><section className="p-6 sm:p-9"><p className="text-sm text-zinc-600">Current status</p><div className="mt-3"><JobStatusMark status={job.status} /></div><h2 className="mt-8 text-4xl font-black tracking-[-0.06em]">{statusTitle(job.status)}</h2><p className="mt-4 max-w-xl leading-relaxed text-zinc-700">{statusText(job.status)}</p><div className="mt-10 grid gap-px bg-black sm:grid-cols-3"><Info label="File" value={job.fileName} /><Info label="Print" value={`${job.colorMode} · ${job.sides}`} /><Info label="Copies" value={`${job.copies} × ${job.paperName}`} /></div>{!finished && <p className="mt-6 text-xs font-bold uppercase tracking-[0.12em] text-zinc-500">This page refreshes automatically.</p>}<Link href="/" className="mt-10 inline-flex items-center gap-2 text-xs font-black uppercase tracking-[0.12em]"><ArrowLeft className="h-4 w-4" /> Back to PrintKori</Link></section><aside className="flex flex-col justify-between bg-[#e32718] p-6 text-white sm:p-9"><div>{job.status === "Completed" ? <CheckCircle2 className="h-10 w-10" /> : job.status === "Failed" ? <CircleAlert className="h-10 w-10" /> : <Loader2 className="h-10 w-10 animate-spin" />}<p className="mt-8 text-xs font-bold uppercase tracking-[0.15em] text-white/70">Total</p><p className="mt-2 text-3xl font-black tracking-[-0.06em]">{`${(job.priceCents / 100).toFixed(2)} Tk`}</p></div><p className="text-sm leading-relaxed text-white/85">{job.customerReference ? `Reference: ${job.customerReference}` : "Keep this page open to follow your order."}</p></aside></div></div></main>;
}

function Info({ label, value }: { label: string; value: string }) { return <div className="bg-white p-4"><p className="text-[10px] font-black uppercase tracking-[0.12em] text-zinc-500">{label}</p><p className="mt-1 truncate text-sm font-bold">{value}</p></div>; }
function statusTitle(status: string) { return ({ Submitted: "REQUEST RECEIVED.", Pending: "WAITING FOR APPROVAL.", Approved: "PRINTING WILL START SOON.", Printing: "YOUR DOCUMENT IS PRINTING.", Completed: "PRINTING IS COMPLETE.", Failed: "THE PRINT COULD NOT FINISH.", Cancelled: "THIS REQUEST WAS CANCELLED." } as Record<string, string>)[status]; }
function statusText(status: string) { return ({ Submitted: "Your request has been received.", Pending: "The shop is waiting to confirm your payment before printing.", Approved: "The shop approved your request and the print computer will collect it.", Printing: "The shop print computer is processing your document now.", Completed: "The print agent confirmed the job as Completed. Please collect it from the shop.", Failed: "The shop has been alerted. Please speak with the counter for help.", Cancelled: "The shop cancelled this request. Please speak with the counter if you need assistance." } as Record<string, string>)[status]; }
